services:
  - type: web
    name: data-science-portafolio-api
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
